# Generated by Django 5.0.14 on 2025-06-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentView',
        ),
    ]
