# Generated by Django 5.0.14 on 2025-07-31 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ODKAuditLogs",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("form", "Form"),
                            ("submission", "Submission"),
                            ("user", "User"),
                        ],
                        default=None,
                        max_length=30,
                        verbose_name="Resource Type",
                    ),
                ),
                ("resource_id", models.BigIntegerField(verbose_name="Resource ID")),
                ("details", models.JSONField(verbose_name="Details")),
                ("success", models.BooleanField(default=True, verbose_name="Success")),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "ODK Audit Log",
                "verbose_name_plural": "ODK Audit Logs",
                "db_table": "odk_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="ODKProjects",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "odk_id",
                    models.BigIntegerField(unique=True, verbose_name="ODK Project ID"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Project name")),
                (
                    "description",
                    models.TextField(null=True, verbose_name="Description"),
                ),
                (
                    "Archived",
                    models.BooleanField(default=False, verbose_name="Archived"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last synchronization"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="ODKProjectPermissions",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("read", "View Project"),
                            ("contribute", "Project Contributor"),
                            ("manage", "Project Manager"),
                            ("administrator", "Project Administrator"),
                        ],
                        default="read",
                        max_length=100,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Granted by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="odk.odkprojects",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Permission",
                "verbose_name_plural": "Project Permissions",
                "db_table": "project_permissions",
            },
        ),
        migrations.CreateModel(
            name="ODKUserSessions",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("odk_token", models.CharField(verbose_name="Odk Token")),
                (
                    "token_expired_at",
                    models.DateTimeField(null=True, verbose_name="Odk Token Expired"),
                ),
                (
                    "actor_id",
                    models.BigIntegerField(null=True, verbose_name="Odk Actor ID"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sycosur User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "odk_user_sessions",
            },
        ),
    ]
