# Generated by Django 5.0.14 on 2025-07-14 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ODKAuditLog",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("project", "Projet"),
                            ("form", "Formulaire"),
                            ("submission", "Soumission"),
                            ("user", "Utilisateur"),
                        ],
                        max_length=50,
                        verbose_name="Type de ressource",
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(max_length=100, verbose_name="ID de ressource"),
                ),
                ("details", models.JSONField(default=dict, verbose_name="Détails")),
                ("success", models.BooleanField(default=True, verbose_name="Succès")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit ODK",
                "verbose_name_plural": "Journaux d'audit ODK",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ODKProject",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("odk_id", models.IntegerField(unique=True, verbose_name="ID ODK")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du projet"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_odk_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet ODK",
                "verbose_name_plural": "Projets ODK",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ODKUserSession",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("odk_token", models.TextField(verbose_name="Token ODK")),
                (
                    "token_expires_at",
                    models.DateTimeField(verbose_name="Expiration du token"),
                ),
                (
                    "odk_account_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID du compte ODK",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_session",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session ODK",
                "verbose_name_plural": "Sessions ODK",
            },
        ),
        migrations.CreateModel(
            name="ODKForm",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("odk_id", models.CharField(max_length=255, verbose_name="ID ODK")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom du formulaire"),
                ),
                ("version", models.CharField(max_length=50, verbose_name="Version")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("closing", "En fermeture"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=50,
                        verbose_name="État",
                    ),
                ),
                (
                    "submissions_count",
                    models.IntegerField(
                        default=0, verbose_name="Nombre de soumissions"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière synchronisation"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="odk.odkproject",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulaire ODK",
                "verbose_name_plural": "Formulaires ODK",
                "ordering": ["-created_at"],
                "unique_together": {("project", "odk_id")},
            },
        ),
        migrations.CreateModel(
            name="ODKProjectPermission",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("read", "Lecture seule"),
                            ("contribute", "Peut soumettre"),
                            ("manage", "Peut gérer les formulaires"),
                            ("admin", "Administrateur"),
                        ],
                        default="read",
                        max_length=20,
                        verbose_name="Niveau de permission",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_odk_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Accordé par",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="odk.odkproject",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odk_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission ODK",
                "verbose_name_plural": "Permissions ODK",
                "unique_together": {("user", "project")},
            },
        ),
    ]
