# Generated by Django 5.0.14 on 2025-08-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="odkprojects",
            old_name="Archived",
            new_name="archived",
        ),
    ]
