# Generated by Django 5.0.14 on 2025-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0002_rename_archived_odkprojects_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odkprojects",
            name="odk_id",
            field=models.BigIntegerField(
                null=True, unique=True, verbose_name="ODK Project ID"
            ),
        ),
    ]
