# Generated by Django 5.0.14 on 2025-08-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0003_alter_odkprojects_odk_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odkprojects",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Project name"
            ),
        ),
    ]
