# Generated by Django 5.0.14 on 2025-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0004_alter_odkprojects_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odkauditlogs",
            name="resource_id",
            field=models.CharField(verbose_name="Resource ID"),
        ),
    ]
