# Generated by Django 5.0.14 on 2025-08-22 15:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0005_alter_odkauditlogs_resource_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ODKAuditLogs",
            new_name="AuditLogs",
        ),
        migrations.RenameModel(
            old_name="ODKProjectPermissions",
            new_name="ProjectPermissions",
        ),
        migrations.RenameModel(
            old_name="ODKProjects",
            new_name="Projects",
        ),
        migrations.AlterModelOptions(
            name="auditlogs",
            options={
                "verbose_name": "Sycosur Audit Log",
                "verbose_name_plural": "Sycosur Audit Logs",
            },
        ),
        # Make table rename idempotent: only rename if destination doesn't already exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.tables
                                WHERE table_schema = 'public' AND table_name = 'audit_logs'
                            ) THEN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.tables
                                    WHERE table_schema = 'public' AND table_name = 'odk_audit_logs'
                                ) THEN
                                    ALTER TABLE public.odk_audit_logs RENAME TO audit_logs;
                                END IF;
                            END IF;
                        END
                        $$;
                        """
                    ),
                    reverse_sql=(
                        """
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.tables
                                WHERE table_schema = 'public' AND table_name = 'odk_audit_logs'
                            ) THEN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.tables
                                    WHERE table_schema = 'public' AND table_name = 'audit_logs'
                                ) THEN
                                    ALTER TABLE public.audit_logs RENAME TO odk_audit_logs;
                                END IF;
                            END IF;
                        END
                        $$;
                        """
                    ),
                )
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name="auditlogs",
                    table="audit_logs",
                )
            ],
        ),
    ]
