# Generated by Django 5.0.14 on 2025-08-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0006_rename_odkauditlogs_auditlogs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="ProjectPermissions",
        ),
        migrations.DeleteModel(
            name="Projects",
        ),
    ]
