# Generated by Django 5.2.6 on 2025-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("odk", "0007_remove_projects_created_by_delete_projectpermissions_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogs",
        ),
    ]
