# Generated by Django 5.0.14 on 2025-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="occupation",
        ),
        migrations.AddField(
            model_name="profile",
            name="odk_role",
            field=models.CharField(
                choices=[
                    ("data_collector", "Data Collector"),
                    ("supervisor", "Supervisor"),
                    ("manager", "Manager"),
                    ("administrator", "Administrator"),
                ],
                default="data_collector",
                max_length=20,
                verbose_name="ODK Role",
            ),
        ),
    ]
