# Generated by Django 5.0.14 on 2025-07-15 16:34

from django.db import migrations, models

import core_apps.common.drive_storage
import core_apps.profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_occupation_profile_odk_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=core_apps.common.drive_storage.GoogleDriveStorage(),
                upload_to=core_apps.profiles.models.avatar_upload_path,
                verbose_name="Avatar",
            ),
        ),
    ]
